name: apk_renamer_cli
description: A sample command-line application.
version: 1.0.2
# repository: https://github.com/my_org/my_repo

publish_to: 'none'

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  path: 1.8.3
  logger: 2.0.2+1
  args: 2.4.2
  renamer_lib:
    path: ../renamer_lib
  parser_apk_info:
    path: ../../parser_apk_info

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: 2.4.7
  pubspec_generator: 4.0.0

